DROP SCHEMA IF EXISTS anura;
CREATE SCHEMA anura;
USE anura;

CREATE TABLE playable_character(
    character_id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    character_name VARCHAR(50) NOT NULL,
    base_hp SMALLINT UNSIGNED NOT NULL,
    base_speed SMALLINT UNSIGNED NOT NULL,
    base_damage SMALLINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE cards(
    card_id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    card_name VARCHAR(50) NOT NULL,
    card_type VARCHAR(25) NOT NULL,
    effect_value SMALLINT UNSIGNED DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE mobs(
    mob_id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    mob_name VARCHAR(50) NOT NULL,
    base_damage SMALLINT UNSIGNED NOT NULL,
    base_hp SMALLINT UNSIGNED NOT NULL,
    mosquito_reward TINYINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE boss(
    boss_id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    boss_name VARCHAR(50) NOT NULL,
    base_hp SMALLINT UNSIGNED NOT NULL,
    base_damage SMALLINT UNSIGNED NOT NULL,
    mosquito_reward TINYINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE users(
    user_id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sesions(
    sesion_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    sesion_user_id SMALLINT UNSIGNED,
    login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    logout_time TIMESTAMP NULL, -- Cambiado a NULL inicial
    FOREIGN KEY(sesion_user_id) REFERENCES users(user_id) ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE runs(
    run_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    run_sesion_id INT UNSIGNED,
    mosquitoes_collected SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    run_time INT UNSIGNED NOT NULL DEFAULT 0,
    bosses_defeated TINYINT UNSIGNED NOT NULL DEFAULT 0,
    victory BOOLEAN NOT NULL DEFAULT FALSE,
    start_time DATETIME NOT NULL,
    end_time DATETIME DEFAULT NULL,
    FOREIGN KEY(run_sesion_id) REFERENCES sesions(sesion_id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE user_character(
    user_character_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    uc_user_id SMALLINT UNSIGNED NOT NULL,
    uc_character_id TINYINT UNSIGNED DEFAULT 1,
    FOREIGN KEY(uc_user_id) REFERENCES users(user_id) ON UPDATE RESTRICT ON DELETE CASCADE,
    FOREIGN KEY(uc_character_id) REFERENCES playable_character(character_id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE character_cards(
    cc_card_id TINYINT UNSIGNED NOT NULL,
    cc_user_character_id SMALLINT UNSIGNED NOT NULL,
    slot_number TINYINT UNSIGNED NOT NULL,
    card_rank TINYINT UNSIGNED NOT NULL,
    PRIMARY KEY (cc_user_character_id, slot_number), 
    FOREIGN KEY (cc_card_id) REFERENCES cards(card_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (cc_user_character_id) REFERENCES user_character(user_character_id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE run_stages(
    stage_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    rs_run_id INT UNSIGNED,
    stage_number TINYINT UNSIGNED NOT NULL,
    FOREIGN KEY(rs_run_id) REFERENCES runs(run_id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE run_mob(
    rm_mob_id TINYINT UNSIGNED,
    rm_run_id INT UNSIGNED,
    mobs_killed TINYINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (rm_mob_id, rm_run_id),
    FOREIGN KEY(rm_mob_id) REFERENCES mobs(mob_id) ON UPDATE CASCADE ON DELETE RESTRICT, 
    FOREIGN KEY(rm_run_id) REFERENCES runs(run_id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE run_boss(
    run_boss_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    rb_boss_id TINYINT UNSIGNED,
    rb_run_id INT UNSIGNED,
    time_to_defeat INT UNSIGNED NOT NULL,
    defeated BOOLEAN NOT NULL,
    FOREIGN KEY(rb_boss_id) REFERENCES boss(boss_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(rb_run_id) REFERENCES runs(run_id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;